version: "3.7"
services:
  #Laravel App
  app:
    build:
      args:
        user: cabinet
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: cabinet-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mynetwork_cabinet

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: cabinet-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - mynetwork_cabinet
  #Mysl Service

  db:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - mynetwork_cabinet

networks:
  mynetwork_cabinet:
    driver: bridge
